# 私有库
source 'http://gitlab.devops.kaishustory.com/ios/KSPrivateCocoaPods.git'
#  常用三方仓库备份中转库
source 'http://gitlab.devops.kaishustory.com/ios/KSThirdPartCocoaPods.git'

#use_frameworks!
use_modular_headers!

platform :ios, '9.0'

target 'KSUI_Example' do
  pod 'KSUI', :path => '../'

  target 'KSUI_Tests' do
    inherit! :search_paths
  end
end
